controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController
      joints:
        - shoulder_pan_joint
        - shoulder_lift_joint
        - elbow_joint
        - wrist_1_joint
        - wrist_2_joint
        - wrist_3_joint

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - shoulder_pan_joint
        - shoulder_lift_joint
        - elbow_joint
        - wrist_1_joint
        - wrist_2_joint
        - wrist_3_joint
      state_publish_rate: 25
      action_monitor_rate: 10
      constraints:
        goal_time: 0.5
        stopped_velocity_tolerance: 0.01
      stop_trajectory_duration: 0.5
      allow_partial_joints_goal: true