controller_manager:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    # Position Controllers ---------------------------------------
    shoulder_pan_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: shoulder_pan_joint
      pid: {p: 8000.0, i: 1=20.0, d: 10.0}
    shoulder_lift_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: shoulder_lift_joint
      pid: {p: 8000.0, i: 20.0, d: 10.0}
    elbow_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: elbow_joint
      pid: {p: 8000.0, i: 20.0, d: 10.0}
    wrist_1_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: wrist_1_joint
      pid: {p: 8000.0, i: 0.0, d: 0.0}
    wrist_2_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: wrist_2_joint
      pid: {p: 8000.0, i: 20.0, d: 0.0}
    wrist_3_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: wrist_3_joint
      pid: {p: 2000.0, i: 80.0, d: 0.0}